In [1]:
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

In [27]:
abc = np.array([[-1.2074, -0.5123, -1.2789, -0.0438,  0.,     -1.5874],
[-0.4835, -1.4969, -1.8752, -1.4927,  0.,     -0.1546],
 [-1.5437,  0.,     -1.5565, -0.4011, -0.914, -0.8054],
 [-2.844,  -3.121,  -1.4508, -0.8052, -3.5132, -0.2493],
 [-2.0608, -1.8476, -2.6464, -0.4739, -1.1374, -1.8606]])

In [39]:
asd = np.random.randint(0, 10, 10)

asd

array([5, 2, 5, 9, 4, 8, 9, 1, 6, 0])

In [51]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.sum(abc, axis=1, keepdims=1)

array([[ -4.6298],
       [ -5.5029],
       [ -5.2207],
       [-11.9835],
       [-10.0267]])

In [9]:
softmax(abc)

array([[0.02150115, 0.04308635, 0.02001749, 0.06883458, 0.07191654,
        0.0147038 ],
       [0.04434528, 0.01609657, 0.01102655, 0.01616432, 0.07191654,
        0.06161506],
       [0.01536061, 0.07191654, 0.01516524, 0.0481541 , 0.02883259,
        0.03214016],
       [0.004185  , 0.00317246, 0.01685599, 0.03214659, 0.00214321,
        0.05604788],
       [0.00915872, 0.01133512, 0.00509932, 0.04477304, 0.02306016,
        0.01118872],
       [0.01228533, 0.05110622, 0.00260441, 0.01235803, 0.01166049,
        0.01802584]])

In [10]:
tf.nn.softmax(abc)

<tf.Tensor: id=4, shape=(6, 6), dtype=float64, numpy=
array([[0.08956575, 0.17948166, 0.08338538, 0.28673918, 0.29957746,
        0.06125056],
       [0.20050829, 0.07278105, 0.04985684, 0.07308737, 0.32517243,
        0.27859402],
       [0.07260322, 0.33991964, 0.07167982, 0.22760445, 0.13627968,
        0.15191319],
       [0.03653389, 0.02769468, 0.14714821, 0.28063091, 0.01870967,
        0.48928264],
       [0.08754683, 0.10835077, 0.0487436 , 0.42797888, 0.2204286 ,
        0.10695133],
       [0.11371064, 0.47302912, 0.02410591, 0.11438351, 0.1079272 ,
        0.16684362]])>

In [2]:
import numpy as np

In [71]:
y = np.ndarray(3)
y

array([1., 1., 1.])

In [84]:
np.append(y, y, axis=0)

array([1., 1., 1., 1., 1., 1.])

In [56]:
np.multiply(y, 0.08)

array([0.08, 0.08, 0.08])

In [40]:
np.where(y!=0, 0, y)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])